### ISSUE TITLE
Would you be open to convert this package to TypeScript?

### ISSUE THREAD

**Issue by hansl** [Rich-Harris/magic-string#116]
Hello,

The Angular-CLI team uses this extensively to do refactoring of TypeScript. I notice you don't have typings and, although we don't _need_ them, it would be nice to have on our side.

I actually propose to convert your project to TypeScript, myself. It wouldn't be much work as I've been doing it for other projects as well, and your code is already well structured. Normally for bigger projects it's a big deal but yours seems to be mainly maintained by yourself.

So no work from you except telling me that a PR is welcome :)  I'll also include build steps so you would only need to do `npm run build` or similar, before publishing.

Let me know!

**Comment by hansl** [comment]
@Rich-Harris What do you think?

**Comment by Rich-Harris** [comment]
Sorry for the non-response, been busy on other projects. Thanks very much for the offer :beers:

I'm *interested* in TypeScript, though I haven't bothered to use it anywhere yet because frankly the setup seemed like a bit of a pain. But if you're able to submit a PR so I can see how it all fits together then maybe I'll become a convert!

I guess my main concern is that there'll be ongoing maintenance costs. Is it easy to back out of if it becomes burdensome?

**Comment by hansl** [comment]
No problem, anytime!

> Is it easy to back out of if it becomes burdensome?

Relatively. You'll see the amount of work from my PR. Stay tuned.

**Comment by mourner** [comment]
We now maintain [TypeScript definitions](https://github.com/Rich-Harris/magic-string/blob/master/index.d.ts) for this project, so I think we can close this for now.

**Comment by Rich-Harris** [comment]
I'd still be up for porting the project over at some point (saves the work of maintaining the bindings) but agree it's not a priority
