### ISSUE TITLE
Incorrect output when magicString.appendLeft > magicString.overwrite

### ISSUE THREAD

**Issue by ismail-codar** [Rich-Harris/magic-string#120]
I want to show you an example. Rather than tell.

This is correct output normally.
```javascript
const magicString = new MagicString(`a + b;`)
magicString.overwrite(4, 5, "c")
console.log(magicString.toString()) // a + c;
```
But this is incorrect output.

```javascript
const magicString = new MagicString(`a + b`)
magicString.appendLeft(5, ";")
console.log(magicString.toString()) // a + b;
console.log("-------------------------------")
magicString.overwrite(4, 5, "c") // a + c (where is the ; character)
console.log(magicString.toString())
```
Problem in second example the last character is eaten.

**Comment by Rich-Harris** [comment]
This is expected behaviour — the `;` character 'belongs' to the character that it's appended to, so if you replace that character you remove the `;` as well.

The way to avoid this is to use the `contentOnly` option (documentation [here](https://github.com/Rich-Harris/magic-string#soverwrite-start-end-content-options-)):

```diff
const magicString = new MagicString(`a + b`)
magicString.appendLeft(5, ";")
console.log(magicString.toString()) // a + b;
console.log("-------------------------------")
-magicString.overwrite(4, 5, "c") // a + c (where is the ; character)
+magicString.overwrite(4, 5, "c", {contentOnly: true}) // a + c;
console.log(magicString.toString())
```

Here's a demo: https://runkit.com/rich/592997adf48c2a00125cfec8

**Comment by ismail-codar** [comment]
Thanks for very quick response. My problem is related to https://github.com/wix/tspoon/blob/master/src/mutable-source-code.ts#L28
