### ISSUE TITLE
Import existing sourcemap

### ISSUE THREAD

**Issue by IvanSanchez** [Rich-Harris/magic-string#13]
Author of [gobble-include](https://github.com/IvanSanchez/gobble-include) here.

My workflow with gobble-include is set up in such a way that the files used by gobble-include as input already have sourcemaps. Right now these must be ignored (which is not a big deal, really) because magic-string doesn't handle them.

It would be nice if magic-string would have some way of importing an existing sourcemap, preferably in the constructor.

This would mean some extra complexity due to the current assumption of just one source file.

**Comment by Rich-Harris** [comment]
It *should* Just Work™ - the theory is that each step should only have to worry about its own sourcemap, otherwise *everybody* has to worry about *everybody else's* sourcemap, which is just never going to happen. Gobble works some magic at the end of the build to compose all the intermediate sourcemaps into a single one that represents the entire chain of transformations.

To make that work, it needs to be able to find the original sources. In this case, I would guess what is happening is that it traces as far back as gobble-include, but then can't find gobble-include's sources. The easiest way to make them 'visible' is to use absolute paths - so [this code](https://github.com/IvanSanchez/gobble-include/blob/master/include.js#L64-L71) might look like this instead:

```js
var inputfile = path.resolve( inputdir, filename );
var outputfile = path.resolve( outputdir, filename );

// We need to add a sourceMappingURL comment, magic-string doesn't add it automatically
var outputcontent = magicString.toString() + '\n//# sourceMappingURL=' + filename + '.map';

return sander.writeFile( outputfile, outputcontent ).then(
  // note the `return` - without that, the transformer will complete as soon
  // as the outputfile is written, which you might get away with but might not!
  return sander.writeFile( outputfile + '.map', magicString.generateMap({ 
    file: outputfile,
    source: inputfile,
    hires: true 
  }));
);
```

As I say, that should work in theory. In practice sourcemaps are tricky devils, so report back if it doesn't work!

**Comment by IvanSanchez** [comment]
Cool, I'll try this later, hopefully this evening. Thanks for having a look at my code :-)

For pretty obvious reasons, gobble-include *wants* to worry about everybody elses's sourcemap, but I'm quite afraid of the level of complexity this might entail.

**Comment by IvanSanchez** [comment]
Nice, it works OK (kinda), see IvanSanchez/gobble-include@6ea95fa0. Now [MandelbrotGL](https://github.com/IvanSanchez/Leaflet.MandelbrotGL) builds sourcemaps as expected, which is ver cool :-)

I'm still annoyed at magic-string not able to put several sources in a sourcemap. But anyway this is not critical at all for my use case, so I don't really care much. I can always revisit the issue when/if it becomes a problem.

**Comment by Rich-Harris** [comment]
Ah, I think I misunderstood the problem - you need to be able to specify the source at [this point](https://github.com/IvanSanchez/gobble-include/blob/master/include.js?ts=4#L63), when includes are inserted. Is that right?

There is `MagicString.Bundle`, which can assemble multiple sources (used for things like [Rollup](https://github.com/rollup/rollup), which is an ES6 module bundler), though getting it work for this might take some hackery. I'm not sure if it's possible to add more sourcemap smarts to `magicString.overwrite()` without significantly complicating the internals, but I'll have a think...

**Comment by IvanSanchez** [comment]
> you need to be able to specify the source at this point, when includes are inserted. Is that right?

Exactly. The problem right now is that any included file will be ignored in the final sourcemap, and will be invisible to the developer.

Furthermore, there probably are two cases: one where the included files already have a sourcemap (because they've been transpiled earlier), and one where they don't (and I expect a one-to-one sourcemap to be generated).
