### ISSUE TITLE
no hires source map where the appendLeft inserted 

### ISSUE THREAD

**Issue by jasonlyu123** [Rich-Harris/magic-string#187]
We use this library to transform svelte code to power editor features in [language-tools](https://github.com/sveltejs/language-tools). And use the source map to map character to character back to the original code. 

When using `appendLeft` and `prependLeft` with `hires: true` the position where the `appendLeft` inserted is not included in the mapping. So it is mapped to the previous character. In our use case, it causes the error or warning to be highlighted one character less than it should be, for example like this:

![圖片](https://user-images.githubusercontent.com/36730922/104296647-dd867380-54fc-11eb-9762-7b3cf25db6e8.png)

Here is a test case for the situation
```ts
it('should correctly map content before append', () => {
    const s = new MagicString('function Foo () {}');

    s.appendLeft(8, '*'); // test will pass if this line is removed

    const map = s.generateMap({
        hires: true,
        file: 'output.js',
        source: 'input.js',
        includeContent: true
    });

    const smc = new SourceMapConsumer(map);
    
    const loc = smc.originalPositionFor({ line: 1, column: 8 });
    assert.strictEqual(loc.line, 1);
    assert.strictEqual(loc.column, 8); // failed here 7 !== 8
});
```

**Comment by dummdidumm** [comment]
I think that's actually correct behavior. `*` is the new 8th character and since it belongs to the previous character (at least that's how I interpreft `...Left`) the correct position is 7. 
What feels wrong to me though is that the same happens when you do `...Right`, which to my understanding means "it belongs to the current character", which is the 8th character in the original, but `originalPositionFor` also returns 7 in this case.

**Comment by jasonlyu123** [comment]
Ah, maybe we are just mapping the wrong character. That is we should map the character before the end of the range and add the offset back to the mapped position.

**Comment by dummdidumm** [comment]
I think you have fallen into the same trap I have before, that is, having a wrong understand of where append/prepend left/right is placed. I thought in the beginning that it means you would have character X and could add something before or afterwards. But what MagicString actually does it adding EVERYTHING before X. So this 
```js
str.prependLeft('Pl', 0);
str.appendLeft('Al', 0);
str.prependRight('Pr', 0);
str.appendRight('Ar', 0);
```

will ALWAYS (no matter the order in this case because each method is used once) result in `PlAlPrArX`.

**Comment by jasonlyu123** [comment]
Yeah, it' kind of confusing. It does make more sense after reading the source and understanding the chunk concept though. I think what I confused about in this situation is the column index of source mapping and where the edit applied. I'll close this because as you mentioned it is the correct behaviour and the `Right` one doesn't seem to be causing the problem I mentioned. Also, in my test, the mapping to the previous character does help in some cases.
