### ISSUE TITLE
type is wrong `This expression is not constructable`

### ISSUE THREAD

**Issue by loynoir** [Rich-Harris/magic-string#251]
https://github.com/microsoft/TypeScript/issues/54166

just a quick fix

```sh
$ ln -rsf node_modules/magic-string/index.d.{ts,mts}
```

```patch
diff --git a/node_modules/magic-string/package.json b/node_modules/magic-string/package.json
index 42c2a99..3842bfe 100644
--- a/node_modules/magic-string/package.json
+++ b/node_modules/magic-string/package.json
@@ -19,7 +19,7 @@
   "exports": {
     "./package.json": "./package.json",
     ".": {
-      "types": "./index.d.ts",
+      "types": "./index.d.mts",
       "import": "./dist/magic-string.es.mjs",
       "require": "./dist/magic-string.cjs.js"
     }
```

**Comment by freddy38510** [comment]
@loynoir Did you try to replace the [line](https://github.com/Rich-Harris/magic-string/blob/2d1fc91c73b167856369eaf373c71ad09c1a27cc/index.d.ts#L118) `export default class MagicString {` by ` export = class MagicString {` ?

With commonjs, the current behavior maps the MagicString class to `module.exports.default`.
Using ` export =` instead of ` export default` will map the MagicString  class to `module.exports`.

You'll find a more detailed explanation of  the `export =` syntax [here](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require).
